name: Build C64 Program File

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download Kick Assembler
      run: wget https://resheim.net/files/KickAss.jar
    - name: Build .prg file
      run: |
        mkdir target
        java -jar KickAss.jar -o target/itema.prg itema.asm
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Application
        # Directory containing files to upload
        path: ./target/
