name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download Kick Assembler
      run: wget https://resheim.net/files/KickAss.jar
    - name: Build .prg file
      run: java -jar KickAss.jar -o itema.prg itema.asm
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: itema.prg
        # Directory containing files to upload
        path: ./
